# Generated by Django 4.2 on 2023-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registrationuser_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('Password', models.CharField(max_length=120, verbose_name='password')),
                ('Email', models.CharField(max_length=255, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationUser',
        ),
    ]
